DELETE FROM FIRESTATION;
INSERT INTO FIRESTATION (ADDRESS, STATION) VALUES ('ADRESSE_1', 1);
INSERT INTO FIRESTATION (ADDRESS, STATION) VALUES ('ADRESSE_2', 2);
INSERT INTO FIRESTATION (ADDRESS, STATION) VALUES ('ADRESSE_3', 3);
INSERT INTO FIRESTATION (ADDRESS, STATION) VALUES ('ADRESSE_4', 1);
INSERT INTO FIRESTATION (ADDRESS, STATION) VALUES ('ADRESSE_5', 2);


